ALTER TABLE t_supplier ADD CONSTRAINT supplier_PK
    PRIMARY KEY (id_supplier);

ALTER TABLE t_supply ADD CONSTRAINT supply_PK
    PRIMARY KEY (id_supply);

ALTER TABLE t_supply ADD CONSTRAINT fk_supply_supplier
    FOREIGN KEY (id_supplier)
    REFERENCES t_supplier(id_supplier);

ALTER TABLE T_SUPPLY_STR ADD CONSTRAINT supply_str_PK
    PRIMARY KEY (id_supply_str);

ALTER TABLE T_SUPPLY_STR ADD CONSTRAINT fk_supply_str_supply
    FOREIGN KEY (ID_SUPPLY)
    REFERENCES T_SUPPLY(ID_SUPPLY);

ALTER TABLE T_WARE ADD CONSTRAINT ware_PK
    PRIMARY KEY (ID_WARE);

ALTER TABLE T_SUPPLY_STR ADD CONSTRAINT fk_supply_str_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

ALTER TABLE T_CTL_NODE ADD CONSTRAINT ctl_node_PK
    PRIMARY KEY (ID_CTL_NODE);

ALTER TABLE T_MODEL ADD CONSTRAINT model_PK
    PRIMARY KEY (ID_MODEL);

ALTER TABLE T_MODEL ADD CONSTRAINT fk_vodel_node
    FOREIGN KEY (ID_NODE)
    REFERENCES T_CTL_NODE(ID_CTL_NODE);

ALTER TABLE T_PRICE_MODEL ADD CONSTRAINT fk_price_model_model
    FOREIGN KEY (ID_MODEL)
    REFERENCES T_MODEL(ID_MODEL);

ALTER TABLE T_DEPT ADD CONSTRAINT dept_PK
    PRIMARY KEY (ID_DEPT);

ALTER TABLE T_CLIENT ADD CONSTRAINT client_PK
    PRIMARY KEY (ID_CLIENT);

ALTER TABLE T_CLIENT ADD CONSTRAINT fk_client_dept
    FOREIGN KEY (ID_DEPT)
    REFERENCES T_DEPT(ID_DEPT);

ALTER TABLE T_SALE ADD CONSTRAINT sale_PK
    PRIMARY KEY (ID_SALE);

ALTER TABLE T_SALE ADD CONSTRAINT fk_sale_client
    FOREIGN KEY (ID_CLIENT)
    REFERENCES T_CLIENT(ID_CLIENT);

ALTER TABLE T_SALE_STR ADD CONSTRAINT sale_str_PK
    PRIMARY KEY (ID_SALE_STR);

ALTER TABLE T_SALE_STR ADD CONSTRAINT  fk_sale
    FOREIGN KEY (ID_SALE)
    REFERENCES T_SALE(ID_SALE);

ALTER TABLE T_SALE_STR ADD CONSTRAINT  fk_sale_str_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

ALTER TABLE T_REST ADD CONSTRAINT fk_rest_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

ALTER TABLE T_REST_HIST ADD CONSTRAINT fk_rest_hist_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

ALTER TABLE T_PRICE_WARE ADD CONSTRAINT fk_price_ware_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

ALTER TABLE T_SALE_REP ADD CONSTRAINT fk_sale_rep_ware
    FOREIGN KEY (ID_WARE)
    REFERENCES T_WARE(ID_WARE);

COMMIT;