-- Найти товары, цены на которые отличаются от цены на модель.
SELECT T_WARE.NAME, T_WARE.PRICE, T_MODEL.PRICE
FROM T_WARE
JOIN T_MODEL ON T_WARE.ID_MODEL = T_MODEL.ID_MODEL
WHERE T_WARE.PRICE <> T_MODEL.PRICE;